# Generated by Django 5.1.5 on 2025-01-20 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Product Name')),
                ('price', models.FloatField(verbose_name='Product Price')),
                ('p_details', models.CharField(max_length=500, verbose_name='Product Details')),
                ('category', models.IntegerField(choices=[(1, 'Baby'), (2, 'Hair'), (3, 'Perfumes'), (4, 'Mens'), (5, 'Skin'), (6, 'Women')], verbose_name='Product Category')),
                ('brand', models.CharField(blank=True, max_length=50, null=True, verbose_name='Brand Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Available')),
                ('pimage', models.ImageField(upload_to='images', verbose_name='Product Image')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=30, verbose_name='Username')),
                ('Email', models.EmailField(default='noemail@example.com', max_length=30, verbose_name='Email')),
                ('Phone', models.IntegerField(verbose_name='Phone')),
                ('Password', models.CharField(max_length=20, verbose_name='Password')),
                ('Confirm_Password', models.CharField(max_length=20, verbose_name='Confirm Password')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ellart_de_soie.product')),
            ],
        ),
    ]
